version: "3.9"

services:
  app:
    build:
      context: ./ # Dockerfile/URL Path
      dockerfile: Dockerfile
    image: dinghao188/rcore-tutorial:dev # imageName:tag
    tty: true # == `docker -t`
    stdin_open: true # == `docker -i`
    volumes:
      - ./:/mnt/
